/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int arr[] = { 2, 3, 4, 10, 40 };
        int n = arr.length;
        int x = 30;
        int result = BinarySearch(arr, 0, n - 1, x);
        if (result == -1)
            System.out.println("Element not exist");
        else
            System.out.println("Element found at index " + result);
        }
    public static int BinarySearch(int arr[], int firstIndex, int lastIndex, int x) {
        if (lastIndex >= firstIndex) {
            int mid = firstIndex + (lastIndex - firstIndex) / 2;
            if (arr[mid] == x)
                return mid;
            if (arr[mid] > x)
                return BinarySearch(arr, firstIndex, mid - 1, x);
            return BinarySearch(arr, mid + 1, lastIndex, x);
        }
        return -1;
    }

}
