/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int arr[] = { 15,20,22,35,50 };
        int x = 22;
        int result = BinarySearch(arr, x);
        if (result == -1)
            System.out.println("the element not exist");
        else
            System.out.println("exist at index " + result);
    }
    public static int BinarySearch(int arr[], int x) {
        int firstElement = 0, lastElement = arr.length - 1;
        while (firstElement <= lastElement) {
            int midElement = firstElement + (lastElement - firstElement) / 2;
            if (arr[midElement] == x)
                return midElement;
            if (arr[midElement] < x)
                firstElement = midElement + 1;
            else
                lastElement = midElement - 1;
        }
        return -1;
    }

}
