/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        int [] arr={1,2,3,4,5,6};
        ArrayList<Integer> newArr=insertShiftArray(arr,15);
        for (int i = 0; i < newArr.size(); i++) {
            System.out.println(newArr.get(i));
        }
    }
    public static ArrayList<Integer> insertShiftArray(int [] arr,int n){
        ArrayList<Integer> newArr = new ArrayList<Integer>();
        int firstHalfLen=(int) Math.ceil((double) arr.length/2);
        for (int i = 0; i < firstHalfLen; i++) {
            newArr.add((arr[i]));
        }
        newArr.add(n);
        for (int i = firstHalfLen; i < arr.length; i++) {
            newArr.add((arr[i]));
        }
        return newArr;
    }

}
