/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

public class App {

    public static void main(String[] args) {
        LinkedList list1=new LinkedList();
        list1.insert(50);
        list1.insert(100);
        list1.insert(150);
        list1.insert(200);
        System.out.println("-------------------------------");
        int value=10;
        System.out.println("Does the linked list include ("+value+") : "+list1.includes(value));
        System.out.println("-------------------------------");

        Node head= list1.head;
        if (head==null){
            System.out.println("------------------------------");
            System.out.println("The linked list is Empty!");
            System.out.println("-------------------------------");
        }else {
            System.out.println("-------------------------------");
            System.out.println("the linked list elements :");
            Node current = head;
            while (current != null) {
                System.out.println(current.value);
                current = current.next;
            }
            System.out.println("-------------------------------");

        }
        System.out.println("-------------------------------");
        System.out.println(list1.toString());
        System.out.println("-------------------------------");


    }
}
